version: "3"
    
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: pass1234
    
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.3-php7.4-apache
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass1234
      WORDPRESS_DB_NAME: wordpress
